/**
 * `<ReviewReport>` — `@react-pdf/renderer` React component that renders
 * the per-label PDF audit artifact.
 *
 * Layout (top → bottom):
 *   1. Header  — proofLens wordmark + app version
 *   2. Metadata — reviewer name, completed-at timestamp, beverage type,
 *                 brand, rules version
 *   3. Image   — the 256-px thumbnail (data: URL passed in by the caller —
 *                 keeps this component pure / sync / server-safe)
 *   4. Field-by-field table — expected vs extracted, status, confidence
 *   5. Overall verdict — pass/fail/etc. styled pill
 *   6. Human override section — only if at least one field carries
 *      `humanOverride`
 *   7. Reviewer notes — `decision.notes` (audit field)
 *   8. § 16.21 footer — canonical compliance statement
 *   9. Signature line — "Final decision is the reviewer's responsibility."
 *
 * The thumbnail-not-original disclaimer is in the footer per the data-
 * handling policy: originals never leave the request that produced them.
 *
 * Fonts: we deliberately avoid loading custom fonts here. `@react-pdf/
 * renderer` ships Helvetica / Times-Roman / Courier as built-ins; using
 * those keeps the bundle small and removes a source of Vercel cold-start
 * failures. If we want Inter later, register it from `public/fonts/`.
 */

import { Document, Page, Text, View, Image, StyleSheet } from "@react-pdf/renderer";
import type { Review } from "@/lib/storage/types";
import type {
  FieldResult,
  FieldStatus,
  OverallStatus,
} from "@/lib/verify/types";

/**
 * Builds the § 16.21 footer line. We thread `rulesVersion` from the
 * persisted Review (default `ttb-2026-04-30`) instead of hard-coding a
 * date so the audit footer always reflects the ruleset the review was
 * verified against — handy when later deployments revise the canonical
 * text. The version slug carries the verification date already.
 */
function buildRulesFooter(rulesVersion: string): string {
  // ttb-2026-04-30 → Apr 30, 2026
  const dateMatch = /^ttb-(\d{4})-(\d{2})-(\d{2})$/.exec(rulesVersion);
  if (!dateMatch) {
    return `Government warning text was checked against 27 CFR § 16.21 (rules ${rulesVersion}).`;
  }
  const [, year, month, day] = dateMatch as unknown as [
    string,
    string,
    string,
    string,
  ];
  return `Government warning text was checked against 27 CFR § 16.21 (verified ${year}-${month}-${day}).`;
}

const THUMBNAIL_FOOTER_NOTE =
  "Image is the 256px thumbnail; originals are not retained per the data-handling policy.";

const SIGNATURE_LINE =
  "This review was generated by proofLens. Final decision is the reviewer's responsibility.";

const STATUS_LABEL: Record<FieldStatus, string> = {
  pass: "Pass",
  "likely-match": "Likely match",
  warning: "Warning",
  fail: "Fail",
  missing: "Missing",
  "low-confidence": "Low confidence",
  "manual-review": "Manual review",
  "not-required": "Not required",
};

/**
 * Verdict pill colours per overall status (PRD §9.6). White text on a
 * status-coloured background — chosen to read clearly when printed in
 * grayscale (each colour has a different luminance) and to stay legible
 * on screen at PDF preview zoom.
 */
const VERDICT_COLOURS: Record<OverallStatus, string> = {
  pass: "#16a34a", // green-600
  "pass-with-warnings": "#d97706", // amber-600
  fail: "#dc2626", // red-600
  "needs-manual-review": "#2563eb", // blue-600
  "request-better-image": "#6b7280", // gray-500
};

const VERDICT_LABEL: Record<OverallStatus, string> = {
  pass: "Pass",
  "pass-with-warnings": "Pass with warnings",
  fail: "Fail",
  "needs-manual-review": "Needs manual review",
  "request-better-image": "Request better image",
};

/**
 * Format an ISO-8601 timestamp as a stable, human-readable UTC string.
 * Using `Intl.DateTimeFormat('en-US', ...)` so the server-rendered PDF
 * is deterministic regardless of the request's locale or timezone — the
 * audit-of-record must not vary by reviewer machine.
 *
 * Output looks like: `Apr 29, 2026, 12:00 PM UTC`.
 */
const COMPLETED_AT_FORMATTER = new Intl.DateTimeFormat("en-US", {
  timeZone: "UTC",
  year: "numeric",
  month: "short",
  day: "2-digit",
  hour: "2-digit",
  minute: "2-digit",
  hour12: true,
});

function formatCompletedAt(iso: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return iso; // fall back to raw on bad input
  return `${COMPLETED_AT_FORMATTER.format(date)} UTC`;
}

const styles = StyleSheet.create({
  page: {
    paddingTop: 36,
    paddingBottom: 48,
    paddingHorizontal: 40,
    fontSize: 9,
    fontFamily: "Helvetica",
    color: "#111827",
    lineHeight: 1.4,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    paddingBottom: 8,
    marginBottom: 12,
  },
  brand: { fontSize: 14, fontFamily: "Helvetica-Bold" },
  brandSub: { color: "#6b7280", fontSize: 8 },
  versionTag: { color: "#6b7280", fontSize: 8 },
  metadataGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 10,
  },
  metadataCell: { width: "50%", marginBottom: 4, paddingRight: 6 },
  metadataLabel: {
    fontSize: 7,
    color: "#6b7280",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  metadataValue: { fontSize: 10 },
  thumbnail: {
    width: 256,
    height: 256,
    objectFit: "contain",
    marginVertical: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    marginTop: 10,
    marginBottom: 4,
  },
  table: {
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderColor: "#e5e7eb",
    marginBottom: 8,
  },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#f3f4f6",
    fontFamily: "Helvetica-Bold",
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderColor: "#e5e7eb",
  },
  cell: {
    padding: 4,
    borderRightWidth: 1,
    borderColor: "#e5e7eb",
    fontSize: 8,
  },
  cellField: { width: "20%" },
  cellExpected: { width: "30%" },
  cellExtracted: { width: "30%" },
  cellStatus: { width: "12%" },
  cellConfidence: { width: "8%" },
  verdictPill: {
    marginTop: 4,
    marginBottom: 8,
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 999,
    alignSelf: "flex-start",
  },
  verdictLabel: {
    color: "#ffffff",
    fontSize: 7,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  verdictValue: {
    color: "#ffffff",
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
  },
  overrideRow: {
    borderTopWidth: 1,
    borderColor: "#e5e7eb",
    paddingVertical: 4,
  },
  notesBlock: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 4,
    padding: 6,
    marginBottom: 8,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    fontSize: 7,
    color: "#6b7280",
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 6,
  },
  signature: {
    marginTop: 16,
    paddingTop: 6,
    borderTopWidth: 1,
    borderColor: "#9ca3af",
    fontSize: 8,
    color: "#374151",
  },
});

function fmtCellValue(value: string | number | boolean | null): string {
  if (value === null) return "—";
  if (typeof value === "boolean") return value ? "yes" : "no";
  return String(value);
}

interface ReviewReportProps {
  review: Review;
  /**
   * `data:` URL of the 256-px JPEG thumbnail. The caller decodes the Blob
   * once and passes a string so this component stays pure / sync.
   */
  thumbnailDataUrl: string;
  /** App version, e.g. from `package.json#version`. */
  appVersion: string;
}

export function ReviewReport({
  review,
  thumbnailDataUrl,
  appVersion,
}: ReviewReportProps) {
  const overrideRows = review.fieldResults.filter(
    (fr): fr is FieldResult & { humanOverride: NonNullable<FieldResult["humanOverride"]> } =>
      Boolean(fr.humanOverride),
  );
  const decisionText = review.decision?.decision ?? "no decision";
  const reviewerNotes = review.decision?.notes ?? "";

  return (
    <Document
      title={`proofLens review — ${review.brand}`}
      author={review.reviewerName}
      creator="proofLens"
      producer="proofLens"
    >
      <Page size="LETTER" style={styles.page} wrap>
        {/* 1. Header */}
        <View style={styles.headerRow}>
          <View>
            <Text style={styles.brand}>proofLens</Text>
            <Text style={styles.brandSub}>
              Alcohol-label compliance review
            </Text>
          </View>
          <Text style={styles.versionTag}>v{appVersion}</Text>
        </View>

        {/* 2. Metadata */}
        <View style={styles.metadataGrid}>
          <View style={styles.metadataCell}>
            <Text style={styles.metadataLabel}>Brand</Text>
            <Text style={styles.metadataValue}>{review.brand}</Text>
          </View>
          <View style={styles.metadataCell}>
            <Text style={styles.metadataLabel}>Beverage type</Text>
            <Text style={styles.metadataValue}>{review.beverageType}</Text>
          </View>
          <View style={styles.metadataCell}>
            <Text style={styles.metadataLabel}>Reviewer</Text>
            <Text style={styles.metadataValue}>{review.reviewerName}</Text>
          </View>
          <View style={styles.metadataCell}>
            <Text style={styles.metadataLabel}>Completed at</Text>
            <Text style={styles.metadataValue}>
              {formatCompletedAt(review.createdAt)}
            </Text>
          </View>
          <View style={styles.metadataCell}>
            <Text style={styles.metadataLabel}>Rules version</Text>
            <Text style={styles.metadataValue}>{review.rulesVersion}</Text>
          </View>
          <View style={styles.metadataCell}>
            <Text style={styles.metadataLabel}>Review id</Text>
            <Text style={styles.metadataValue}>{review.id}</Text>
          </View>
        </View>

        {/* 3. Thumbnail.
            `@react-pdf/renderer` <Image> doesn't support an alt prop —
            jsx-a11y is a DOM-side rule and we suppress it here. */}
        {thumbnailDataUrl ? (
          // eslint-disable-next-line jsx-a11y/alt-text
          <Image src={thumbnailDataUrl} style={styles.thumbnail} />
        ) : null}

        {/* 4. Field-by-field table */}
        <Text style={styles.sectionTitle}>Verification details</Text>
        <View style={styles.table}>
          <View style={styles.tableHeaderRow}>
            <Text style={[styles.cell, styles.cellField]}>Field</Text>
            <Text style={[styles.cell, styles.cellExpected]}>Expected</Text>
            <Text style={[styles.cell, styles.cellExtracted]}>Extracted</Text>
            <Text style={[styles.cell, styles.cellStatus]}>Status</Text>
            <Text style={[styles.cell, styles.cellConfidence]}>Conf.</Text>
          </View>
          {review.fieldResults.map((fr) => (
            <View style={styles.tableRow} key={fr.field} wrap={false}>
              <Text style={[styles.cell, styles.cellField]}>{fr.label}</Text>
              <Text style={[styles.cell, styles.cellExpected]}>
                {fmtCellValue(fr.expected)}
              </Text>
              <Text style={[styles.cell, styles.cellExtracted]}>
                {fmtCellValue(fr.value)}
              </Text>
              <Text style={[styles.cell, styles.cellStatus]}>
                {STATUS_LABEL[fr.status]}
              </Text>
              <Text style={[styles.cell, styles.cellConfidence]}>
                {fr.confidence.toFixed(2)}
              </Text>
            </View>
          ))}
        </View>

        {/* 5. Overall verdict — coloured pill keyed off OverallStatus. */}
        <Text style={styles.sectionTitle}>Overall verdict</Text>
        <View
          style={[
            styles.verdictPill,
            { backgroundColor: VERDICT_COLOURS[review.overall] },
          ]}
        >
          <Text style={styles.verdictLabel}>Verdict</Text>
          <Text style={styles.verdictValue}>
            {VERDICT_LABEL[review.overall]}
          </Text>
        </View>
        <Text style={styles.metadataValue}>
          Final decision: {decisionText}
        </Text>

        {/* 6. Human overrides — only when present */}
        {overrideRows.length > 0 ? (
          <>
            <Text style={styles.sectionTitle}>Human overrides</Text>
            {overrideRows.map((fr) => (
              <View style={styles.overrideRow} key={`ov-${fr.field}`} wrap={false}>
                <Text style={styles.metadataValue}>
                  {fr.label}: AI: {fr.humanOverride.originalAiStatus} →
                  {" "}Human: {fr.humanOverride.humanStatus}
                </Text>
                <Text style={styles.metadataLabel}>
                  Reason
                </Text>
                <Text style={styles.metadataValue}>
                  {fr.humanOverride.reason || "(no reason given)"}
                </Text>
                <Text style={styles.brandSub}>
                  by {fr.humanOverride.reviewerName} at {fr.humanOverride.timestamp}
                </Text>
              </View>
            ))}
          </>
        ) : null}

        {/* 7. Reviewer notes */}
        {reviewerNotes ? (
          <>
            <Text style={styles.sectionTitle}>Reviewer notes</Text>
            <View style={styles.notesBlock}>
              <Text>{reviewerNotes}</Text>
            </View>
          </>
        ) : null}

        {/* Signature line */}
        <View style={styles.signature}>
          <Text>{SIGNATURE_LINE}</Text>
          <Text style={styles.brandSub}>
            Reviewer: {review.reviewerName}
          </Text>
        </View>

        {/* Footer (fixed) */}
        <View style={styles.footer} fixed>
          <Text>{buildRulesFooter(review.rulesVersion)}</Text>
          <Text>{THUMBNAIL_FOOTER_NOTE}</Text>
        </View>
      </Page>
    </Document>
  );
}

ReviewReport.displayName = "ReviewReport";
